#!/bin/bash

# grc-password-generator
# (c) Copyright 2015 Muhammad Panji - sumodirjo at gmail dot com
# This script download and parse password Generator page from grc.com (https://www.grc.com/passwords.htm)

password_page=https://www.grc.com/passwords.htm

echo "Downloading $password_page"
wget -c $password_page -o /dev/null

echo ""

echo "Parsing 64 random hexadecimal characters (0-9 and A-F)"
random_hexadecimal=$(grep courier passwords.htm | grep hexadecimal | awk -F '[<>]' {'print $21'} | head -1)

echo "Parsing 63 random printable ASCII characters"
random_printable=$(grep courier passwords.htm | grep printable | awk -F '[<>]' {'print $21'} | head -1)

echo "Parsing 63 random alpha-numeric characters (a-z, A-Z, 0-9)"
random_alphanumeric=$(grep courier passwords.htm | grep alpha-numeric | awk -F '[<>]' {'print $21'} | head -1)

echo ""

echo "64 random hexadecimal characters (0-9 and A-F): " $random_hexadecimal
echo "63 random printable ASCII characters: " $random_printable
echo "63 random alpha-numeric characters (a-z, A-Z, 0-9): " $random_alphanumeric


echo "Cleaning up"
rm -f passwords.htm